// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXqjoD3dQ3r2EL4lntG-u4s4jEWzrr6x8',
    appId: '1:434480421710:web:59d893ca61666c89dd1c1f',
    messagingSenderId: '434480421710',
    projectId: 'ash-92101',
    authDomain: 'ash-92101.firebaseapp.com',
    storageBucket: 'ash-92101.firebasestorage.app',
    measurementId: 'G-PYGB7513WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOBq-ztOBNzRzeNHylpbAdvYCc3nkH2iQ',
    appId: '1:434480421710:android:35dcd310075caa56dd1c1f',
    messagingSenderId: '434480421710',
    projectId: 'ash-92101',
    storageBucket: 'ash-92101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2Z2uGDZBGrQ0btoCZxyx63RaFQXH-wk',
    appId: '1:434480421710:ios:75a1d2e16a9c201cdd1c1f',
    messagingSenderId: '434480421710',
    projectId: 'ash-92101',
    storageBucket: 'ash-92101.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker3ash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO2Z2uGDZBGrQ0btoCZxyx63RaFQXH-wk',
    appId: '1:434480421710:ios:75a1d2e16a9c201cdd1c1f',
    messagingSenderId: '434480421710',
    projectId: 'ash-92101',
    storageBucket: 'ash-92101.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker3ash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXqjoD3dQ3r2EL4lntG-u4s4jEWzrr6x8',
    appId: '1:434480421710:web:83b225c67cf07b47dd1c1f',
    messagingSenderId: '434480421710',
    projectId: 'ash-92101',
    authDomain: 'ash-92101.firebaseapp.com',
    storageBucket: 'ash-92101.firebasestorage.app',
    measurementId: 'G-KJF8NFEB2X',
  );
}
